In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

In [ ]:
df_org = pd.read_csv("/content/breast-cancer.csv")

print(df_org.shape)

df_org.head()

(569, 32)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df = df_org.copy()

df.isna().sum().sum()

np.int64(0)

In [ ]:
# Identify non-numeric columns in the DataFrame
non_numeric_cols = df.select_dtypes(exclude=['number']).columns

print("Non-numeric columns:")
print(list(non_numeric_cols))

Non-numeric columns:
['diagnosis']

In [ ]:
# Convert 'B' to 0 and 'M' to 1 in the 'diagnosis' column
df['diagnosis'] = df['diagnosis'].map({'B': 0, 'M': 1})

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df["diagnosis"].value_counts(normalize=True)

diagnosis
0    0.627417
1    0.372583
Name: proportion, dtype: float64

In [ ]:
df.drop("id", axis=1, inplace=True)

df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=1234)

print("Train Set Shape:", train_df.shape)
print("Test Set Shape:", test_df.shape)

print("\nTrain DataFrame:")
display(train_df)

Train Set Shape: (455, 31)
Test Set Shape: (114, 31)

Train DataFrame:

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
518,0,12.88,18.22,84.45,493.1,0.12180,0.16610,0.04825,0.05303,0.1709,...,15.05,24.37,99.31,674.7,0.14560,0.29610,0.12460,0.10960,0.2582,0.08893
551,0,11.13,22.44,71.49,378.4,0.09566,0.08194,0.04824,0.02257,0.2030,...,12.02,28.26,77.80,436.6,0.10870,0.17820,0.15640,0.06413,0.3169,0.08032
111,0,12.63,20.76,82.15,480.4,0.09933,0.12090,0.10650,0.06021,0.1735,...,13.33,25.47,89.00,527.4,0.12870,0.22500,0.22160,0.11050,0.2226,0.08486
64,1,12.68,23.84,82.69,499.0,0.11220,0.12620,0.11280,0.06873,0.1905,...,17.09,33.47,111.80,888.3,0.18510,0.40610,0.40240,0.17160,0.3383,0.10310
443,0,10.57,18.32,66.82,340.9,0.08142,0.04462,0.01993,0.01111,0.2372,...,10.94,23.31,69.35,366.3,0.09794,0.06542,0.03986,0.02222,0.2699,0.06736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0,13.85,15.18,88.99,587.4,0.09516,0.07688,0.04479,0.03711,0.2110,...,14.98,21.74,98.37,670.0,0.11850,0.17240,0.14560,0.09993,0.2955,0.06912
372,1,21.37,15.10,141.30,1386.0,0.10010,0.15150,0.19320,0.12550,0.1973,...,22.69,21.84,152.10,1535.0,0.11920,0.28400,0.40240,0.19660,0.2730,0.08666
204,0,12.47,18.60,81.09,481.9,0.09965,0.10580,0.08005,0.03821,0.1925,...,14.97,24.64,96.05,677.9,0.14260,0.23780,0.26710,0.10150,0.3014,0.08750
53,1,18.22,18.70,120.30,1033.0,0.11480,0.14850,0.17720,0.10600,0.2092,...,20.60,24.13,135.10,1321.0,0.12800,0.22970,0.26230,0.13250,0.3021,0.07987
294,0,12.72,13.78,81.78,492.1,0.09667,0.08393,0.01288,0.01924,0.1638,...,13.50,17.48,88.54,553.7,0.12980,0.14720,0.05233,0.06343,0.2369,0.06922

In [ ]:
# جدا کردن ویژگی‌ها و هدف
X = train_df.drop(columns=['diagnosis'])  # All columns except 'Exited'
y = train_df['diagnosis']                 # The target column

X_test = test_df.drop(columns=['diagnosis'])
y_test = test_df['diagnosis']

# ۱. مقیاس‌بندی داده‌ها (StandardScaler)
scaler = StandardScaler()

# فیت کردن فقط روی داده‌های آموزشی و تبدیل آن‌ها
X_train_scaled = scaler.fit_transform(X)

# تبدیل داده‌های تست با همان اسکیلر آموزش‌دیده
X_test_scaled = scaler.transform(X_test)

# ۲. ساخت و آموزش مدل KNN با داده‌های مقیاس‌شده
clf_knn = KNeighborsClassifier(n_neighbors=7)
clf_knn.fit(X_train_scaled, y)

# ۳. پیش‌بینی روی داده‌های تست مقیاس‌شده
y_pred = clf_knn.predict(X_test_scaled)

# ۴. ارزیابی مدل
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9385964912280702

Classification Report:
              precision    recall  f1-score   support

           0       0.91      1.00      0.95        69
           1       1.00      0.84      0.92        45

    accuracy                           0.94       114
   macro avg       0.95      0.92      0.93       114
weighted avg       0.94      0.94      0.94       114

In [ ]:
clf_lr = LogisticRegression(random_state=1234, class_weight={0:1, 1:10})
clf_lr.fit(X_train_scaled, y)

y_pred = clf_lr.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9736842105263158

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        69
           1       1.00      0.93      0.97        45

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114